# Generated by Django 2.2.2 on 2019-06-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, null=True)),
                ('model_no', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
